project_id = "hljyovzxisaqkwgvtoky"

[functions.rewrite]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.notify-support]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.tone-checker]
verify_jwt = false